warsztatDjango/urls.py
from django.contrib import admin
from django.urls import path

from reservation import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('rooms_view/', views.rooms_view),
    path('add_room/', views.AddRoom.as_view()),
    path('delete_room/', views.DeleteRoom.as_view()),
    path('modify_room/<int:id>/', views.ModifyRoom.as_view()),
    path('reservation_room/<int:id>/', views.ReservationRoom.as_view()),
    path('detail_room_view/<int:id>/', views.detail_room_view),
]

reservation/models.py
from django.db import models


# Create your models here.


class ConferenceRoom(models.Model):
    name = models.CharField(max_length=255)
    capacity = models.PositiveIntegerField()
    projector_availability = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} {self.capacity} {self.projector_availability}'

    def get_modify_url(self):
        return f'/modify_room/{self.id}/'

    def get_absolute_url(self):
        return f'/detail_room_view/{self.id}/'


class ReservationModel(models.Model):
    date = models.DateField()
    room = models.ForeignKey(ConferenceRoom, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f'{self.date} {self.room} {self.comment}'

    class Meta:
        unique_together = ('date', 'room_id')

reservation/views.py
import datetime

from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View

from reservation.models import ConferenceRoom, ReservationModel


def index(request):
    return render(request, 'base.html')


class AddRoom(View):

    def get(self, request):
        return render(request, 'form_to_add_room.html')

    def post(self, request):
        name = request.POST.get('name')
        capacity = request.POST.get('capacity', 0)
        projector = bool(request.POST.get('projector'))
        if not name:
            return render(request, 'msg.html', {'msg': 'Nazwa sali nie została podana'})
        if int(capacity) < 0:
            return render(request, 'msg.html', {'msg': 'Pojemność sali jest niepoprawna'})
        if ConferenceRoom.objects.filter(name=name):
            return render(request, 'msg.html', {'msg': 'Sala o takiej nazwie już istnieje w bazie danych'})
        cr = ConferenceRoom(name=name, capacity=capacity, projector_availability=projector)
        cr.save()
        return redirect('http://127.0.0.1:8000/')


def rooms_view(request):
    try:
        rooms = ConferenceRoom.objects.all()
        return render(request, 'rooms_view.html', {'rooms': rooms})
    except:
        return render(request, 'msg.html', {'msg': 'Brak dostępnych sal'})


class DeleteRoom(View):

    def get(self, request):
        rooms = ConferenceRoom.objects.all()
        return render(request, 'form_to_del_room.html', {'rooms': rooms})

    def post(self, request):
        try:
            room = request.POST.get('id_room')
            room.delete()
            return redirect('/rooms_view/', 'msg.html', {'msg': 'Sala została usunięta'})
        except:
            return render(request, 'msg.html', {'msg': 'Nie znaleziono sali o takim id'})


class ModifyRoom(View):

    def get(self, request, id):
        room = ConferenceRoom.objects.get(pk=id)
        return render(request, 'change_room.html', {'room': room})

    def post(self, request, id):
        if not request.POST.get('name'):
            return render(request, 'msg.html', {'msg': 'Nazwa sali nie została podana'})
        if int(request.POST.get('capacity', 0)) < 0:
            return render(request, 'msg.html', {'msg': 'Pojemność sali jest niepoprawna'})
        # if ConferenceRoom.objects.filter(name=request.POST.get('name')):
        #     return render(request, 'msg.html', {'msg': 'Sala o takiej nazwie już istnieje w bazie danych'})
        room = ConferenceRoom.objects.get(pk=id)
        room.name = request.POST.get('name')
        room.capacity = request.POST.get('capacity', 0)
        room.projector_availability = bool(request.POST.get('projector'))
        room.save()
        return redirect('/rooms_view/')


class ReservationRoom(View):

    def get(self, request, id):
        return render(request, 'form_to_reservation_room.html', {'room':ConferenceRoom.objects.get(pk=id)})

    def post(self, request, id):
        room = ConferenceRoom.objects.get(pk=id)
        now_date = datetime.date.today()
        date = request.POST.get('date')
        comment = request.POST.get('comment')
        if ReservationModel.objects.filter(room=room, date=date):
            return render(request, 'msg.html', {'msg': f'Sala {room.name} jest już zarezerwowana na ten dzień'})
        if date < str(now_date):
            return render(request, 'msg.html', {'msg': f'{date} to przeszłość'})
        r = ReservationModel()
        r.date = date
        r.room = room
        r.comment = comment
        r.save()
        return redirect('/rooms_view/', 'msg.html', {'msg':'Rezerwacja sali została zapisana'})


def detail_room_view(request, id):
    room = ConferenceRoom.objects.get(pk=id)
    return render(request, 'detail_room_view.html', {'room':room})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rezerwacja sal</title>
    <style>
        #head {
            text-align: center;
            width:100%;
            color: silver;
            float:left;
        }
        #menu {
            width:10%;
            float:left;
        }
        #tresc {
            width:90%;
            float:left;
        }
        #footer {
            position: fixed;
            left: 0;
            bottom: 0;
            text-align: center;
            width:100%;
            color: white;
            background: black;
        }
        #menu h3 {
            margin-left: 30px;
        }
    </style>
</head>
<body>
<div id="head">
    <h1>ZAREZERWÓJ SALĘ MARZEŃ</h1>
</div>

<div id="menu">
    <h3>MENU</h3>
    <ul>
        <li><a href="http://127.0.0.1:8000/">Strona główna</a></li>
        <li><a href="/rooms_view/">Pokaż sale</a></li>
        <li><a href="/add_room/">Dodaj salę</a></li>
        <li><a href="/delete_room/">Usuń salę</a></li>
    </ul>
</div>

<div id="tresc">
    {% block content %}
    jakaś treść
    {% endblock %}
</div>

<div id="footer">
    <b>Autor projektu: <i>Mariusz Śledź</i></b>
</div>
</body>
</html>

templates/change_room.html
{% extends 'base.html' %}

{% block content %}
    <table>
        <form method="post">
        {% csrf_token %}
            <tr><th>Nazwa sali</th><th><input type="text" name="name" value="{{ room.name }}"></th></tr>
            <tr><th>Pojemność sali</th><th><input type="number" name="capacity" value="{{ room.capacity }}"></th></tr>
            <tr><th>Dostępność rzutnika</th><td><input type="checkbox" name="projector"></td></tr>
            <tr><td colspan="2"><input type="submit" value="Modyfikuj salę"></td></tr>
        </form>
    </table>
{% endblock %}

templates/detail_room_view.html
{% extends 'base.html' %}
{% block content %}
<table>
    <tr><th>Nazwa sali:</th><th>{{ room.name }}</th></tr>
    <tr><th>Pojemność sali:</th><th>{{ room.capacity}}</th></tr>
    <tr><th>Projektor w sali:</th><th>{{ room.projector_availability }}</th></tr>
</table>

{% if room %}
    <p><b>Przyszłe rezerwacje:</b></p>
    <table>
        {% for room in room.reservationmodel_set.all %}
        <tr><td>{{ room.date }} -</td><td>{{ room.comment }}</td></tr>
        {% endfor %}
    </table>
{% else %}
    <p>Brak rezerwacji</p>
{% endif %}
{% endblock %}

templates/form_to_add_room.html
{% extends 'base.html' %}

{% block content %}
    <table>
        <form method="post">
        {% csrf_token %}
            <tr><th>Nazwa sali</th><th><input type="text" name="name" placeholder="Nazwa sali"></th></tr>
            <tr><th>Pojemność sali</th><th><input type="number" name="capacity" placeholder="Pojemnosć sali"></th></tr>
            <tr><th>Dostępność rzutnika</th><td><input type="checkbox" name="projector"></td></tr>
            <tr><td colspan="2"><input type="submit" value="Dodaj salę"></td></tr>
        </form>
    </table>
{% endblock %}

templates/form_to_del_room.html
{% extends 'base.html' %}

{% block content %}
    <table>
        <form method="post">
        {% csrf_token %}
            <tr><th>Nazwa sali</th><th>
                <select name="id_room">
                    {% for room in rooms %}
                        <option value="{{ room.id }}">{{ room.name }}</option>
                    {% endfor %}
                </select>
            </th></tr>
            <tr><td colspan="2"><input type="submit" value="Usuń salę"></td></tr>
        </form>
    </table>
{% endblock %}

templates/form_to_reservation_room.html
{% extends 'base.html' %}

{% block content %}
    <h3>Rezerwacja: <b>{{ room.name }}</b></h3>
        <form method="post">
            {% csrf_token %}
            <p><b>Wybierz datę</b></p><input type="date" name="date" >
            <p><b>Komentarz</b></p><textarea name="comment" placeholder="Dodaj komentarz" cols="45" rows="7"></textarea>
            <p><input type="submit" value="Rezerwuję"></p>
        </form>

{% endblock %}

templates/msg.html
{% extends 'base.html' %}

{% block content %}
    <p>{{ msg }}</p>
    <p><input type="button" value="Wróć" onClick="history.back()"></p>
{% endblock %}

templates/rooms_view.html
{% extends 'base.html' %}

{% block content %}
    <table border="1px">
    <tr><th>Nazwa sali</th><th>Pojemność sali</th><th>Dostępność projektora</th><th>Modyfikuj</th></tr>
    {% for room in rooms %}
        <tr><td align="center"><a href="{{ room.get_absolute_url }}">{{ room.name }}</a></td><td align="center">{{ room.capacity }}</td><td align="center">{{ room.projector_availability }}</td><td><a href="{{ room.get_modify_url }}">Modyfikuj</a></td></tr>
    {% endfor %}
    </table>
{% endblock %}